/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mobile_manipulator_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s1[309] = {17, 17, 0, 17, 34, 51, 68, 85, 102, 119, 136, 153, 170, 187, 204, 221, 238, 255, 272, 289, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s2[147] = {17, 8, 0, 17, 34, 51, 68, 85, 102, 119, 136, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s3[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s4[3] = {0, 0, 0};

/* mobile_manipulator_expl_vde_forw:(i0[17],i1[17x17],i2[17x8],i3[8],i4[])->(o0[17],o1[17x17],o2[17x8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][9] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a3=sin(a1);
  a4=(a0*a3);
  if (res[0]!=0) res[0][1]=a4;
  a4=arg[0]? arg[0][10] : 0;
  if (res[0]!=0) res[0][2]=a4;
  a4=arg[0]? arg[0][11] : 0;
  if (res[0]!=0) res[0][3]=a4;
  a4=arg[0]? arg[0][12] : 0;
  if (res[0]!=0) res[0][4]=a4;
  a4=arg[0]? arg[0][13] : 0;
  if (res[0]!=0) res[0][5]=a4;
  a4=arg[0]? arg[0][14] : 0;
  if (res[0]!=0) res[0][6]=a4;
  a4=arg[0]? arg[0][15] : 0;
  if (res[0]!=0) res[0][7]=a4;
  a4=arg[0]? arg[0][16] : 0;
  if (res[0]!=0) res[0][8]=a4;
  a4=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][9]=a4;
  a4=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][10]=a4;
  a4=arg[3]? arg[3][2] : 0;
  if (res[0]!=0) res[0][11]=a4;
  a4=arg[3]? arg[3][3] : 0;
  if (res[0]!=0) res[0][12]=a4;
  a4=arg[3]? arg[3][4] : 0;
  if (res[0]!=0) res[0][13]=a4;
  a4=arg[3]? arg[3][5] : 0;
  if (res[0]!=0) res[0][14]=a4;
  a4=arg[3]? arg[3][6] : 0;
  if (res[0]!=0) res[0][15]=a4;
  a4=arg[3]? arg[3][7] : 0;
  if (res[0]!=0) res[0][16]=a4;
  a4=arg[1]? arg[1][9] : 0;
  a5=(a2*a4);
  a6=sin(a1);
  a7=arg[1]? arg[1][2] : 0;
  a8=(a6*a7);
  a8=(a0*a8);
  a5=(a5-a8);
  if (res[1]!=0) res[1][0]=a5;
  a4=(a3*a4);
  a5=cos(a1);
  a7=(a5*a7);
  a7=(a0*a7);
  a4=(a4+a7);
  if (res[1]!=0) res[1][1]=a4;
  a4=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][2]=a4;
  a4=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][3]=a4;
  a4=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][4]=a4;
  a4=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][5]=a4;
  a4=arg[1]? arg[1][14] : 0;
  if (res[1]!=0) res[1][6]=a4;
  a4=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][7]=a4;
  a4=arg[1]? arg[1][16] : 0;
  if (res[1]!=0) res[1][8]=a4;
  a4=0.;
  if (res[1]!=0) res[1][9]=a4;
  if (res[1]!=0) res[1][10]=a4;
  if (res[1]!=0) res[1][11]=a4;
  if (res[1]!=0) res[1][12]=a4;
  if (res[1]!=0) res[1][13]=a4;
  if (res[1]!=0) res[1][14]=a4;
  if (res[1]!=0) res[1][15]=a4;
  if (res[1]!=0) res[1][16]=a4;
  a7=arg[1]? arg[1][26] : 0;
  a8=(a2*a7);
  a9=arg[1]? arg[1][19] : 0;
  a10=(a6*a9);
  a10=(a0*a10);
  a8=(a8-a10);
  if (res[1]!=0) res[1][17]=a8;
  a7=(a3*a7);
  a9=(a5*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[1]!=0) res[1][18]=a7;
  a7=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][19]=a7;
  a7=arg[1]? arg[1][28] : 0;
  if (res[1]!=0) res[1][20]=a7;
  a7=arg[1]? arg[1][29] : 0;
  if (res[1]!=0) res[1][21]=a7;
  a7=arg[1]? arg[1][30] : 0;
  if (res[1]!=0) res[1][22]=a7;
  a7=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][23]=a7;
  a7=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][24]=a7;
  a7=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][25]=a7;
  if (res[1]!=0) res[1][26]=a4;
  if (res[1]!=0) res[1][27]=a4;
  if (res[1]!=0) res[1][28]=a4;
  if (res[1]!=0) res[1][29]=a4;
  if (res[1]!=0) res[1][30]=a4;
  if (res[1]!=0) res[1][31]=a4;
  if (res[1]!=0) res[1][32]=a4;
  if (res[1]!=0) res[1][33]=a4;
  a7=arg[1]? arg[1][43] : 0;
  a9=(a2*a7);
  a8=arg[1]? arg[1][36] : 0;
  a10=(a6*a8);
  a10=(a0*a10);
  a9=(a9-a10);
  if (res[1]!=0) res[1][34]=a9;
  a7=(a3*a7);
  a8=(a5*a8);
  a8=(a0*a8);
  a7=(a7+a8);
  if (res[1]!=0) res[1][35]=a7;
  a7=arg[1]? arg[1][44] : 0;
  if (res[1]!=0) res[1][36]=a7;
  a7=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][37]=a7;
  a7=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][38]=a7;
  a7=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][39]=a7;
  a7=arg[1]? arg[1][48] : 0;
  if (res[1]!=0) res[1][40]=a7;
  a7=arg[1]? arg[1][49] : 0;
  if (res[1]!=0) res[1][41]=a7;
  a7=arg[1]? arg[1][50] : 0;
  if (res[1]!=0) res[1][42]=a7;
  if (res[1]!=0) res[1][43]=a4;
  if (res[1]!=0) res[1][44]=a4;
  if (res[1]!=0) res[1][45]=a4;
  if (res[1]!=0) res[1][46]=a4;
  if (res[1]!=0) res[1][47]=a4;
  if (res[1]!=0) res[1][48]=a4;
  if (res[1]!=0) res[1][49]=a4;
  if (res[1]!=0) res[1][50]=a4;
  a7=arg[1]? arg[1][60] : 0;
  a8=(a2*a7);
  a9=arg[1]? arg[1][53] : 0;
  a10=(a6*a9);
  a10=(a0*a10);
  a8=(a8-a10);
  if (res[1]!=0) res[1][51]=a8;
  a7=(a3*a7);
  a9=(a5*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[1]!=0) res[1][52]=a7;
  a7=arg[1]? arg[1][61] : 0;
  if (res[1]!=0) res[1][53]=a7;
  a7=arg[1]? arg[1][62] : 0;
  if (res[1]!=0) res[1][54]=a7;
  a7=arg[1]? arg[1][63] : 0;
  if (res[1]!=0) res[1][55]=a7;
  a7=arg[1]? arg[1][64] : 0;
  if (res[1]!=0) res[1][56]=a7;
  a7=arg[1]? arg[1][65] : 0;
  if (res[1]!=0) res[1][57]=a7;
  a7=arg[1]? arg[1][66] : 0;
  if (res[1]!=0) res[1][58]=a7;
  a7=arg[1]? arg[1][67] : 0;
  if (res[1]!=0) res[1][59]=a7;
  if (res[1]!=0) res[1][60]=a4;
  if (res[1]!=0) res[1][61]=a4;
  if (res[1]!=0) res[1][62]=a4;
  if (res[1]!=0) res[1][63]=a4;
  if (res[1]!=0) res[1][64]=a4;
  if (res[1]!=0) res[1][65]=a4;
  if (res[1]!=0) res[1][66]=a4;
  if (res[1]!=0) res[1][67]=a4;
  a7=arg[1]? arg[1][77] : 0;
  a9=(a2*a7);
  a8=arg[1]? arg[1][70] : 0;
  a10=(a6*a8);
  a10=(a0*a10);
  a9=(a9-a10);
  if (res[1]!=0) res[1][68]=a9;
  a7=(a3*a7);
  a8=(a5*a8);
  a8=(a0*a8);
  a7=(a7+a8);
  if (res[1]!=0) res[1][69]=a7;
  a7=arg[1]? arg[1][78] : 0;
  if (res[1]!=0) res[1][70]=a7;
  a7=arg[1]? arg[1][79] : 0;
  if (res[1]!=0) res[1][71]=a7;
  a7=arg[1]? arg[1][80] : 0;
  if (res[1]!=0) res[1][72]=a7;
  a7=arg[1]? arg[1][81] : 0;
  if (res[1]!=0) res[1][73]=a7;
  a7=arg[1]? arg[1][82] : 0;
  if (res[1]!=0) res[1][74]=a7;
  a7=arg[1]? arg[1][83] : 0;
  if (res[1]!=0) res[1][75]=a7;
  a7=arg[1]? arg[1][84] : 0;
  if (res[1]!=0) res[1][76]=a7;
  if (res[1]!=0) res[1][77]=a4;
  if (res[1]!=0) res[1][78]=a4;
  if (res[1]!=0) res[1][79]=a4;
  if (res[1]!=0) res[1][80]=a4;
  if (res[1]!=0) res[1][81]=a4;
  if (res[1]!=0) res[1][82]=a4;
  if (res[1]!=0) res[1][83]=a4;
  if (res[1]!=0) res[1][84]=a4;
  a7=arg[1]? arg[1][94] : 0;
  a8=(a2*a7);
  a9=arg[1]? arg[1][87] : 0;
  a10=(a6*a9);
  a10=(a0*a10);
  a8=(a8-a10);
  if (res[1]!=0) res[1][85]=a8;
  a7=(a3*a7);
  a9=(a5*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[1]!=0) res[1][86]=a7;
  a7=arg[1]? arg[1][95] : 0;
  if (res[1]!=0) res[1][87]=a7;
  a7=arg[1]? arg[1][96] : 0;
  if (res[1]!=0) res[1][88]=a7;
  a7=arg[1]? arg[1][97] : 0;
  if (res[1]!=0) res[1][89]=a7;
  a7=arg[1]? arg[1][98] : 0;
  if (res[1]!=0) res[1][90]=a7;
  a7=arg[1]? arg[1][99] : 0;
  if (res[1]!=0) res[1][91]=a7;
  a7=arg[1]? arg[1][100] : 0;
  if (res[1]!=0) res[1][92]=a7;
  a7=arg[1]? arg[1][101] : 0;
  if (res[1]!=0) res[1][93]=a7;
  if (res[1]!=0) res[1][94]=a4;
  if (res[1]!=0) res[1][95]=a4;
  if (res[1]!=0) res[1][96]=a4;
  if (res[1]!=0) res[1][97]=a4;
  if (res[1]!=0) res[1][98]=a4;
  if (res[1]!=0) res[1][99]=a4;
  if (res[1]!=0) res[1][100]=a4;
  if (res[1]!=0) res[1][101]=a4;
  a7=arg[1]? arg[1][111] : 0;
  a9=(a2*a7);
  a8=arg[1]? arg[1][104] : 0;
  a10=(a6*a8);
  a10=(a0*a10);
  a9=(a9-a10);
  if (res[1]!=0) res[1][102]=a9;
  a7=(a3*a7);
  a8=(a5*a8);
  a8=(a0*a8);
  a7=(a7+a8);
  if (res[1]!=0) res[1][103]=a7;
  a7=arg[1]? arg[1][112] : 0;
  if (res[1]!=0) res[1][104]=a7;
  a7=arg[1]? arg[1][113] : 0;
  if (res[1]!=0) res[1][105]=a7;
  a7=arg[1]? arg[1][114] : 0;
  if (res[1]!=0) res[1][106]=a7;
  a7=arg[1]? arg[1][115] : 0;
  if (res[1]!=0) res[1][107]=a7;
  a7=arg[1]? arg[1][116] : 0;
  if (res[1]!=0) res[1][108]=a7;
  a7=arg[1]? arg[1][117] : 0;
  if (res[1]!=0) res[1][109]=a7;
  a7=arg[1]? arg[1][118] : 0;
  if (res[1]!=0) res[1][110]=a7;
  if (res[1]!=0) res[1][111]=a4;
  if (res[1]!=0) res[1][112]=a4;
  if (res[1]!=0) res[1][113]=a4;
  if (res[1]!=0) res[1][114]=a4;
  if (res[1]!=0) res[1][115]=a4;
  if (res[1]!=0) res[1][116]=a4;
  if (res[1]!=0) res[1][117]=a4;
  if (res[1]!=0) res[1][118]=a4;
  a7=arg[1]? arg[1][128] : 0;
  a8=(a2*a7);
  a9=arg[1]? arg[1][121] : 0;
  a10=(a6*a9);
  a10=(a0*a10);
  a8=(a8-a10);
  if (res[1]!=0) res[1][119]=a8;
  a7=(a3*a7);
  a9=(a5*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[1]!=0) res[1][120]=a7;
  a7=arg[1]? arg[1][129] : 0;
  if (res[1]!=0) res[1][121]=a7;
  a7=arg[1]? arg[1][130] : 0;
  if (res[1]!=0) res[1][122]=a7;
  a7=arg[1]? arg[1][131] : 0;
  if (res[1]!=0) res[1][123]=a7;
  a7=arg[1]? arg[1][132] : 0;
  if (res[1]!=0) res[1][124]=a7;
  a7=arg[1]? arg[1][133] : 0;
  if (res[1]!=0) res[1][125]=a7;
  a7=arg[1]? arg[1][134] : 0;
  if (res[1]!=0) res[1][126]=a7;
  a7=arg[1]? arg[1][135] : 0;
  if (res[1]!=0) res[1][127]=a7;
  if (res[1]!=0) res[1][128]=a4;
  if (res[1]!=0) res[1][129]=a4;
  if (res[1]!=0) res[1][130]=a4;
  if (res[1]!=0) res[1][131]=a4;
  if (res[1]!=0) res[1][132]=a4;
  if (res[1]!=0) res[1][133]=a4;
  if (res[1]!=0) res[1][134]=a4;
  if (res[1]!=0) res[1][135]=a4;
  a7=arg[1]? arg[1][145] : 0;
  a9=(a2*a7);
  a8=arg[1]? arg[1][138] : 0;
  a10=(a6*a8);
  a10=(a0*a10);
  a9=(a9-a10);
  if (res[1]!=0) res[1][136]=a9;
  a7=(a3*a7);
  a8=(a5*a8);
  a8=(a0*a8);
  a7=(a7+a8);
  if (res[1]!=0) res[1][137]=a7;
  a7=arg[1]? arg[1][146] : 0;
  if (res[1]!=0) res[1][138]=a7;
  a7=arg[1]? arg[1][147] : 0;
  if (res[1]!=0) res[1][139]=a7;
  a7=arg[1]? arg[1][148] : 0;
  if (res[1]!=0) res[1][140]=a7;
  a7=arg[1]? arg[1][149] : 0;
  if (res[1]!=0) res[1][141]=a7;
  a7=arg[1]? arg[1][150] : 0;
  if (res[1]!=0) res[1][142]=a7;
  a7=arg[1]? arg[1][151] : 0;
  if (res[1]!=0) res[1][143]=a7;
  a7=arg[1]? arg[1][152] : 0;
  if (res[1]!=0) res[1][144]=a7;
  if (res[1]!=0) res[1][145]=a4;
  if (res[1]!=0) res[1][146]=a4;
  if (res[1]!=0) res[1][147]=a4;
  if (res[1]!=0) res[1][148]=a4;
  if (res[1]!=0) res[1][149]=a4;
  if (res[1]!=0) res[1][150]=a4;
  if (res[1]!=0) res[1][151]=a4;
  if (res[1]!=0) res[1][152]=a4;
  a7=arg[1]? arg[1][162] : 0;
  a8=(a2*a7);
  a9=arg[1]? arg[1][155] : 0;
  a10=(a6*a9);
  a10=(a0*a10);
  a8=(a8-a10);
  if (res[1]!=0) res[1][153]=a8;
  a7=(a3*a7);
  a9=(a5*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[1]!=0) res[1][154]=a7;
  a7=arg[1]? arg[1][163] : 0;
  if (res[1]!=0) res[1][155]=a7;
  a7=arg[1]? arg[1][164] : 0;
  if (res[1]!=0) res[1][156]=a7;
  a7=arg[1]? arg[1][165] : 0;
  if (res[1]!=0) res[1][157]=a7;
  a7=arg[1]? arg[1][166] : 0;
  if (res[1]!=0) res[1][158]=a7;
  a7=arg[1]? arg[1][167] : 0;
  if (res[1]!=0) res[1][159]=a7;
  a7=arg[1]? arg[1][168] : 0;
  if (res[1]!=0) res[1][160]=a7;
  a7=arg[1]? arg[1][169] : 0;
  if (res[1]!=0) res[1][161]=a7;
  if (res[1]!=0) res[1][162]=a4;
  if (res[1]!=0) res[1][163]=a4;
  if (res[1]!=0) res[1][164]=a4;
  if (res[1]!=0) res[1][165]=a4;
  if (res[1]!=0) res[1][166]=a4;
  if (res[1]!=0) res[1][167]=a4;
  if (res[1]!=0) res[1][168]=a4;
  if (res[1]!=0) res[1][169]=a4;
  a7=arg[1]? arg[1][179] : 0;
  a9=(a2*a7);
  a8=arg[1]? arg[1][172] : 0;
  a10=(a6*a8);
  a10=(a0*a10);
  a9=(a9-a10);
  if (res[1]!=0) res[1][170]=a9;
  a7=(a3*a7);
  a8=(a5*a8);
  a8=(a0*a8);
  a7=(a7+a8);
  if (res[1]!=0) res[1][171]=a7;
  a7=arg[1]? arg[1][180] : 0;
  if (res[1]!=0) res[1][172]=a7;
  a7=arg[1]? arg[1][181] : 0;
  if (res[1]!=0) res[1][173]=a7;
  a7=arg[1]? arg[1][182] : 0;
  if (res[1]!=0) res[1][174]=a7;
  a7=arg[1]? arg[1][183] : 0;
  if (res[1]!=0) res[1][175]=a7;
  a7=arg[1]? arg[1][184] : 0;
  if (res[1]!=0) res[1][176]=a7;
  a7=arg[1]? arg[1][185] : 0;
  if (res[1]!=0) res[1][177]=a7;
  a7=arg[1]? arg[1][186] : 0;
  if (res[1]!=0) res[1][178]=a7;
  if (res[1]!=0) res[1][179]=a4;
  if (res[1]!=0) res[1][180]=a4;
  if (res[1]!=0) res[1][181]=a4;
  if (res[1]!=0) res[1][182]=a4;
  if (res[1]!=0) res[1][183]=a4;
  if (res[1]!=0) res[1][184]=a4;
  if (res[1]!=0) res[1][185]=a4;
  if (res[1]!=0) res[1][186]=a4;
  a7=arg[1]? arg[1][196] : 0;
  a8=(a2*a7);
  a9=arg[1]? arg[1][189] : 0;
  a10=(a6*a9);
  a10=(a0*a10);
  a8=(a8-a10);
  if (res[1]!=0) res[1][187]=a8;
  a7=(a3*a7);
  a9=(a5*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[1]!=0) res[1][188]=a7;
  a7=arg[1]? arg[1][197] : 0;
  if (res[1]!=0) res[1][189]=a7;
  a7=arg[1]? arg[1][198] : 0;
  if (res[1]!=0) res[1][190]=a7;
  a7=arg[1]? arg[1][199] : 0;
  if (res[1]!=0) res[1][191]=a7;
  a7=arg[1]? arg[1][200] : 0;
  if (res[1]!=0) res[1][192]=a7;
  a7=arg[1]? arg[1][201] : 0;
  if (res[1]!=0) res[1][193]=a7;
  a7=arg[1]? arg[1][202] : 0;
  if (res[1]!=0) res[1][194]=a7;
  a7=arg[1]? arg[1][203] : 0;
  if (res[1]!=0) res[1][195]=a7;
  if (res[1]!=0) res[1][196]=a4;
  if (res[1]!=0) res[1][197]=a4;
  if (res[1]!=0) res[1][198]=a4;
  if (res[1]!=0) res[1][199]=a4;
  if (res[1]!=0) res[1][200]=a4;
  if (res[1]!=0) res[1][201]=a4;
  if (res[1]!=0) res[1][202]=a4;
  if (res[1]!=0) res[1][203]=a4;
  a7=arg[1]? arg[1][213] : 0;
  a9=(a2*a7);
  a8=arg[1]? arg[1][206] : 0;
  a10=(a6*a8);
  a10=(a0*a10);
  a9=(a9-a10);
  if (res[1]!=0) res[1][204]=a9;
  a7=(a3*a7);
  a8=(a5*a8);
  a8=(a0*a8);
  a7=(a7+a8);
  if (res[1]!=0) res[1][205]=a7;
  a7=arg[1]? arg[1][214] : 0;
  if (res[1]!=0) res[1][206]=a7;
  a7=arg[1]? arg[1][215] : 0;
  if (res[1]!=0) res[1][207]=a7;
  a7=arg[1]? arg[1][216] : 0;
  if (res[1]!=0) res[1][208]=a7;
  a7=arg[1]? arg[1][217] : 0;
  if (res[1]!=0) res[1][209]=a7;
  a7=arg[1]? arg[1][218] : 0;
  if (res[1]!=0) res[1][210]=a7;
  a7=arg[1]? arg[1][219] : 0;
  if (res[1]!=0) res[1][211]=a7;
  a7=arg[1]? arg[1][220] : 0;
  if (res[1]!=0) res[1][212]=a7;
  if (res[1]!=0) res[1][213]=a4;
  if (res[1]!=0) res[1][214]=a4;
  if (res[1]!=0) res[1][215]=a4;
  if (res[1]!=0) res[1][216]=a4;
  if (res[1]!=0) res[1][217]=a4;
  if (res[1]!=0) res[1][218]=a4;
  if (res[1]!=0) res[1][219]=a4;
  if (res[1]!=0) res[1][220]=a4;
  a7=arg[1]? arg[1][230] : 0;
  a8=(a2*a7);
  a9=arg[1]? arg[1][223] : 0;
  a10=(a6*a9);
  a10=(a0*a10);
  a8=(a8-a10);
  if (res[1]!=0) res[1][221]=a8;
  a7=(a3*a7);
  a9=(a5*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[1]!=0) res[1][222]=a7;
  a7=arg[1]? arg[1][231] : 0;
  if (res[1]!=0) res[1][223]=a7;
  a7=arg[1]? arg[1][232] : 0;
  if (res[1]!=0) res[1][224]=a7;
  a7=arg[1]? arg[1][233] : 0;
  if (res[1]!=0) res[1][225]=a7;
  a7=arg[1]? arg[1][234] : 0;
  if (res[1]!=0) res[1][226]=a7;
  a7=arg[1]? arg[1][235] : 0;
  if (res[1]!=0) res[1][227]=a7;
  a7=arg[1]? arg[1][236] : 0;
  if (res[1]!=0) res[1][228]=a7;
  a7=arg[1]? arg[1][237] : 0;
  if (res[1]!=0) res[1][229]=a7;
  if (res[1]!=0) res[1][230]=a4;
  if (res[1]!=0) res[1][231]=a4;
  if (res[1]!=0) res[1][232]=a4;
  if (res[1]!=0) res[1][233]=a4;
  if (res[1]!=0) res[1][234]=a4;
  if (res[1]!=0) res[1][235]=a4;
  if (res[1]!=0) res[1][236]=a4;
  if (res[1]!=0) res[1][237]=a4;
  a7=arg[1]? arg[1][247] : 0;
  a9=(a2*a7);
  a8=arg[1]? arg[1][240] : 0;
  a10=(a6*a8);
  a10=(a0*a10);
  a9=(a9-a10);
  if (res[1]!=0) res[1][238]=a9;
  a7=(a3*a7);
  a8=(a5*a8);
  a8=(a0*a8);
  a7=(a7+a8);
  if (res[1]!=0) res[1][239]=a7;
  a7=arg[1]? arg[1][248] : 0;
  if (res[1]!=0) res[1][240]=a7;
  a7=arg[1]? arg[1][249] : 0;
  if (res[1]!=0) res[1][241]=a7;
  a7=arg[1]? arg[1][250] : 0;
  if (res[1]!=0) res[1][242]=a7;
  a7=arg[1]? arg[1][251] : 0;
  if (res[1]!=0) res[1][243]=a7;
  a7=arg[1]? arg[1][252] : 0;
  if (res[1]!=0) res[1][244]=a7;
  a7=arg[1]? arg[1][253] : 0;
  if (res[1]!=0) res[1][245]=a7;
  a7=arg[1]? arg[1][254] : 0;
  if (res[1]!=0) res[1][246]=a7;
  if (res[1]!=0) res[1][247]=a4;
  if (res[1]!=0) res[1][248]=a4;
  if (res[1]!=0) res[1][249]=a4;
  if (res[1]!=0) res[1][250]=a4;
  if (res[1]!=0) res[1][251]=a4;
  if (res[1]!=0) res[1][252]=a4;
  if (res[1]!=0) res[1][253]=a4;
  if (res[1]!=0) res[1][254]=a4;
  a7=arg[1]? arg[1][264] : 0;
  a8=(a2*a7);
  a9=arg[1]? arg[1][257] : 0;
  a10=(a6*a9);
  a10=(a0*a10);
  a8=(a8-a10);
  if (res[1]!=0) res[1][255]=a8;
  a7=(a3*a7);
  a9=(a5*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[1]!=0) res[1][256]=a7;
  a7=arg[1]? arg[1][265] : 0;
  if (res[1]!=0) res[1][257]=a7;
  a7=arg[1]? arg[1][266] : 0;
  if (res[1]!=0) res[1][258]=a7;
  a7=arg[1]? arg[1][267] : 0;
  if (res[1]!=0) res[1][259]=a7;
  a7=arg[1]? arg[1][268] : 0;
  if (res[1]!=0) res[1][260]=a7;
  a7=arg[1]? arg[1][269] : 0;
  if (res[1]!=0) res[1][261]=a7;
  a7=arg[1]? arg[1][270] : 0;
  if (res[1]!=0) res[1][262]=a7;
  a7=arg[1]? arg[1][271] : 0;
  if (res[1]!=0) res[1][263]=a7;
  if (res[1]!=0) res[1][264]=a4;
  if (res[1]!=0) res[1][265]=a4;
  if (res[1]!=0) res[1][266]=a4;
  if (res[1]!=0) res[1][267]=a4;
  if (res[1]!=0) res[1][268]=a4;
  if (res[1]!=0) res[1][269]=a4;
  if (res[1]!=0) res[1][270]=a4;
  if (res[1]!=0) res[1][271]=a4;
  a7=arg[1]? arg[1][281] : 0;
  a9=(a2*a7);
  a8=arg[1]? arg[1][274] : 0;
  a6=(a6*a8);
  a6=(a0*a6);
  a9=(a9-a6);
  if (res[1]!=0) res[1][272]=a9;
  a7=(a3*a7);
  a5=(a5*a8);
  a5=(a0*a5);
  a7=(a7+a5);
  if (res[1]!=0) res[1][273]=a7;
  a7=arg[1]? arg[1][282] : 0;
  if (res[1]!=0) res[1][274]=a7;
  a7=arg[1]? arg[1][283] : 0;
  if (res[1]!=0) res[1][275]=a7;
  a7=arg[1]? arg[1][284] : 0;
  if (res[1]!=0) res[1][276]=a7;
  a7=arg[1]? arg[1][285] : 0;
  if (res[1]!=0) res[1][277]=a7;
  a7=arg[1]? arg[1][286] : 0;
  if (res[1]!=0) res[1][278]=a7;
  a7=arg[1]? arg[1][287] : 0;
  if (res[1]!=0) res[1][279]=a7;
  a7=arg[1]? arg[1][288] : 0;
  if (res[1]!=0) res[1][280]=a7;
  if (res[1]!=0) res[1][281]=a4;
  if (res[1]!=0) res[1][282]=a4;
  if (res[1]!=0) res[1][283]=a4;
  if (res[1]!=0) res[1][284]=a4;
  if (res[1]!=0) res[1][285]=a4;
  if (res[1]!=0) res[1][286]=a4;
  if (res[1]!=0) res[1][287]=a4;
  if (res[1]!=0) res[1][288]=a4;
  a7=arg[2]? arg[2][9] : 0;
  a5=(a2*a7);
  a8=sin(a1);
  a9=arg[2]? arg[2][2] : 0;
  a6=(a8*a9);
  a6=(a0*a6);
  a5=(a5-a6);
  if (res[2]!=0) res[2][0]=a5;
  a7=(a3*a7);
  a1=cos(a1);
  a9=(a1*a9);
  a9=(a0*a9);
  a7=(a7+a9);
  if (res[2]!=0) res[2][1]=a7;
  a7=arg[2]? arg[2][10] : 0;
  if (res[2]!=0) res[2][2]=a7;
  a7=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][3]=a7;
  a7=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][4]=a7;
  a7=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][5]=a7;
  a7=arg[2]? arg[2][14] : 0;
  if (res[2]!=0) res[2][6]=a7;
  a7=arg[2]? arg[2][15] : 0;
  if (res[2]!=0) res[2][7]=a7;
  a7=arg[2]? arg[2][16] : 0;
  if (res[2]!=0) res[2][8]=a7;
  a7=1.;
  if (res[2]!=0) res[2][9]=a7;
  if (res[2]!=0) res[2][10]=a4;
  if (res[2]!=0) res[2][11]=a4;
  if (res[2]!=0) res[2][12]=a4;
  if (res[2]!=0) res[2][13]=a4;
  if (res[2]!=0) res[2][14]=a4;
  if (res[2]!=0) res[2][15]=a4;
  if (res[2]!=0) res[2][16]=a4;
  a9=arg[2]? arg[2][26] : 0;
  a5=(a2*a9);
  a6=arg[2]? arg[2][19] : 0;
  a10=(a8*a6);
  a10=(a0*a10);
  a5=(a5-a10);
  if (res[2]!=0) res[2][17]=a5;
  a9=(a3*a9);
  a6=(a1*a6);
  a6=(a0*a6);
  a9=(a9+a6);
  if (res[2]!=0) res[2][18]=a9;
  a9=arg[2]? arg[2][27] : 0;
  if (res[2]!=0) res[2][19]=a9;
  a9=arg[2]? arg[2][28] : 0;
  if (res[2]!=0) res[2][20]=a9;
  a9=arg[2]? arg[2][29] : 0;
  if (res[2]!=0) res[2][21]=a9;
  a9=arg[2]? arg[2][30] : 0;
  if (res[2]!=0) res[2][22]=a9;
  a9=arg[2]? arg[2][31] : 0;
  if (res[2]!=0) res[2][23]=a9;
  a9=arg[2]? arg[2][32] : 0;
  if (res[2]!=0) res[2][24]=a9;
  a9=arg[2]? arg[2][33] : 0;
  if (res[2]!=0) res[2][25]=a9;
  if (res[2]!=0) res[2][26]=a4;
  if (res[2]!=0) res[2][27]=a7;
  if (res[2]!=0) res[2][28]=a4;
  if (res[2]!=0) res[2][29]=a4;
  if (res[2]!=0) res[2][30]=a4;
  if (res[2]!=0) res[2][31]=a4;
  if (res[2]!=0) res[2][32]=a4;
  if (res[2]!=0) res[2][33]=a4;
  a9=arg[2]? arg[2][43] : 0;
  a6=(a2*a9);
  a5=arg[2]? arg[2][36] : 0;
  a10=(a8*a5);
  a10=(a0*a10);
  a6=(a6-a10);
  if (res[2]!=0) res[2][34]=a6;
  a9=(a3*a9);
  a5=(a1*a5);
  a5=(a0*a5);
  a9=(a9+a5);
  if (res[2]!=0) res[2][35]=a9;
  a9=arg[2]? arg[2][44] : 0;
  if (res[2]!=0) res[2][36]=a9;
  a9=arg[2]? arg[2][45] : 0;
  if (res[2]!=0) res[2][37]=a9;
  a9=arg[2]? arg[2][46] : 0;
  if (res[2]!=0) res[2][38]=a9;
  a9=arg[2]? arg[2][47] : 0;
  if (res[2]!=0) res[2][39]=a9;
  a9=arg[2]? arg[2][48] : 0;
  if (res[2]!=0) res[2][40]=a9;
  a9=arg[2]? arg[2][49] : 0;
  if (res[2]!=0) res[2][41]=a9;
  a9=arg[2]? arg[2][50] : 0;
  if (res[2]!=0) res[2][42]=a9;
  if (res[2]!=0) res[2][43]=a4;
  if (res[2]!=0) res[2][44]=a4;
  if (res[2]!=0) res[2][45]=a7;
  if (res[2]!=0) res[2][46]=a4;
  if (res[2]!=0) res[2][47]=a4;
  if (res[2]!=0) res[2][48]=a4;
  if (res[2]!=0) res[2][49]=a4;
  if (res[2]!=0) res[2][50]=a4;
  a9=arg[2]? arg[2][60] : 0;
  a5=(a2*a9);
  a6=arg[2]? arg[2][53] : 0;
  a10=(a8*a6);
  a10=(a0*a10);
  a5=(a5-a10);
  if (res[2]!=0) res[2][51]=a5;
  a9=(a3*a9);
  a6=(a1*a6);
  a6=(a0*a6);
  a9=(a9+a6);
  if (res[2]!=0) res[2][52]=a9;
  a9=arg[2]? arg[2][61] : 0;
  if (res[2]!=0) res[2][53]=a9;
  a9=arg[2]? arg[2][62] : 0;
  if (res[2]!=0) res[2][54]=a9;
  a9=arg[2]? arg[2][63] : 0;
  if (res[2]!=0) res[2][55]=a9;
  a9=arg[2]? arg[2][64] : 0;
  if (res[2]!=0) res[2][56]=a9;
  a9=arg[2]? arg[2][65] : 0;
  if (res[2]!=0) res[2][57]=a9;
  a9=arg[2]? arg[2][66] : 0;
  if (res[2]!=0) res[2][58]=a9;
  a9=arg[2]? arg[2][67] : 0;
  if (res[2]!=0) res[2][59]=a9;
  if (res[2]!=0) res[2][60]=a4;
  if (res[2]!=0) res[2][61]=a4;
  if (res[2]!=0) res[2][62]=a4;
  if (res[2]!=0) res[2][63]=a7;
  if (res[2]!=0) res[2][64]=a4;
  if (res[2]!=0) res[2][65]=a4;
  if (res[2]!=0) res[2][66]=a4;
  if (res[2]!=0) res[2][67]=a4;
  a9=arg[2]? arg[2][77] : 0;
  a6=(a2*a9);
  a5=arg[2]? arg[2][70] : 0;
  a10=(a8*a5);
  a10=(a0*a10);
  a6=(a6-a10);
  if (res[2]!=0) res[2][68]=a6;
  a9=(a3*a9);
  a5=(a1*a5);
  a5=(a0*a5);
  a9=(a9+a5);
  if (res[2]!=0) res[2][69]=a9;
  a9=arg[2]? arg[2][78] : 0;
  if (res[2]!=0) res[2][70]=a9;
  a9=arg[2]? arg[2][79] : 0;
  if (res[2]!=0) res[2][71]=a9;
  a9=arg[2]? arg[2][80] : 0;
  if (res[2]!=0) res[2][72]=a9;
  a9=arg[2]? arg[2][81] : 0;
  if (res[2]!=0) res[2][73]=a9;
  a9=arg[2]? arg[2][82] : 0;
  if (res[2]!=0) res[2][74]=a9;
  a9=arg[2]? arg[2][83] : 0;
  if (res[2]!=0) res[2][75]=a9;
  a9=arg[2]? arg[2][84] : 0;
  if (res[2]!=0) res[2][76]=a9;
  if (res[2]!=0) res[2][77]=a4;
  if (res[2]!=0) res[2][78]=a4;
  if (res[2]!=0) res[2][79]=a4;
  if (res[2]!=0) res[2][80]=a4;
  if (res[2]!=0) res[2][81]=a7;
  if (res[2]!=0) res[2][82]=a4;
  if (res[2]!=0) res[2][83]=a4;
  if (res[2]!=0) res[2][84]=a4;
  a9=arg[2]? arg[2][94] : 0;
  a5=(a2*a9);
  a6=arg[2]? arg[2][87] : 0;
  a10=(a8*a6);
  a10=(a0*a10);
  a5=(a5-a10);
  if (res[2]!=0) res[2][85]=a5;
  a9=(a3*a9);
  a6=(a1*a6);
  a6=(a0*a6);
  a9=(a9+a6);
  if (res[2]!=0) res[2][86]=a9;
  a9=arg[2]? arg[2][95] : 0;
  if (res[2]!=0) res[2][87]=a9;
  a9=arg[2]? arg[2][96] : 0;
  if (res[2]!=0) res[2][88]=a9;
  a9=arg[2]? arg[2][97] : 0;
  if (res[2]!=0) res[2][89]=a9;
  a9=arg[2]? arg[2][98] : 0;
  if (res[2]!=0) res[2][90]=a9;
  a9=arg[2]? arg[2][99] : 0;
  if (res[2]!=0) res[2][91]=a9;
  a9=arg[2]? arg[2][100] : 0;
  if (res[2]!=0) res[2][92]=a9;
  a9=arg[2]? arg[2][101] : 0;
  if (res[2]!=0) res[2][93]=a9;
  if (res[2]!=0) res[2][94]=a4;
  if (res[2]!=0) res[2][95]=a4;
  if (res[2]!=0) res[2][96]=a4;
  if (res[2]!=0) res[2][97]=a4;
  if (res[2]!=0) res[2][98]=a4;
  if (res[2]!=0) res[2][99]=a7;
  if (res[2]!=0) res[2][100]=a4;
  if (res[2]!=0) res[2][101]=a4;
  a9=arg[2]? arg[2][111] : 0;
  a6=(a2*a9);
  a5=arg[2]? arg[2][104] : 0;
  a10=(a8*a5);
  a10=(a0*a10);
  a6=(a6-a10);
  if (res[2]!=0) res[2][102]=a6;
  a9=(a3*a9);
  a5=(a1*a5);
  a5=(a0*a5);
  a9=(a9+a5);
  if (res[2]!=0) res[2][103]=a9;
  a9=arg[2]? arg[2][112] : 0;
  if (res[2]!=0) res[2][104]=a9;
  a9=arg[2]? arg[2][113] : 0;
  if (res[2]!=0) res[2][105]=a9;
  a9=arg[2]? arg[2][114] : 0;
  if (res[2]!=0) res[2][106]=a9;
  a9=arg[2]? arg[2][115] : 0;
  if (res[2]!=0) res[2][107]=a9;
  a9=arg[2]? arg[2][116] : 0;
  if (res[2]!=0) res[2][108]=a9;
  a9=arg[2]? arg[2][117] : 0;
  if (res[2]!=0) res[2][109]=a9;
  a9=arg[2]? arg[2][118] : 0;
  if (res[2]!=0) res[2][110]=a9;
  if (res[2]!=0) res[2][111]=a4;
  if (res[2]!=0) res[2][112]=a4;
  if (res[2]!=0) res[2][113]=a4;
  if (res[2]!=0) res[2][114]=a4;
  if (res[2]!=0) res[2][115]=a4;
  if (res[2]!=0) res[2][116]=a4;
  if (res[2]!=0) res[2][117]=a7;
  if (res[2]!=0) res[2][118]=a4;
  a9=arg[2]? arg[2][128] : 0;
  a2=(a2*a9);
  a5=arg[2]? arg[2][121] : 0;
  a8=(a8*a5);
  a8=(a0*a8);
  a2=(a2-a8);
  if (res[2]!=0) res[2][119]=a2;
  a3=(a3*a9);
  a1=(a1*a5);
  a0=(a0*a1);
  a3=(a3+a0);
  if (res[2]!=0) res[2][120]=a3;
  a3=arg[2]? arg[2][129] : 0;
  if (res[2]!=0) res[2][121]=a3;
  a3=arg[2]? arg[2][130] : 0;
  if (res[2]!=0) res[2][122]=a3;
  a3=arg[2]? arg[2][131] : 0;
  if (res[2]!=0) res[2][123]=a3;
  a3=arg[2]? arg[2][132] : 0;
  if (res[2]!=0) res[2][124]=a3;
  a3=arg[2]? arg[2][133] : 0;
  if (res[2]!=0) res[2][125]=a3;
  a3=arg[2]? arg[2][134] : 0;
  if (res[2]!=0) res[2][126]=a3;
  a3=arg[2]? arg[2][135] : 0;
  if (res[2]!=0) res[2][127]=a3;
  if (res[2]!=0) res[2][128]=a4;
  if (res[2]!=0) res[2][129]=a4;
  if (res[2]!=0) res[2][130]=a4;
  if (res[2]!=0) res[2][131]=a4;
  if (res[2]!=0) res[2][132]=a4;
  if (res[2]!=0) res[2][133]=a4;
  if (res[2]!=0) res[2][134]=a4;
  if (res[2]!=0) res[2][135]=a7;
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_manipulator_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mobile_manipulator_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mobile_manipulator_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_manipulator_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mobile_manipulator_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mobile_manipulator_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mobile_manipulator_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void mobile_manipulator_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mobile_manipulator_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int mobile_manipulator_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real mobile_manipulator_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_manipulator_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mobile_manipulator_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_manipulator_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mobile_manipulator_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mobile_manipulator_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
